---
ID: "0e19eb15-1723-4beb-ad83-8e574022041f"
Parent: "861fa3e2-97b5-4600-9541-46d7c415cd62"
Template: "fd2059fd-6043-4dfe-8c04-e2437ce87634"
Path: "/sitecore/content/skate-park/skate-park/Presentation/Partial Designs/Product Content"
SharedFields:
- ID: "55faae90-3bba-4f7f-96fe-13c3f40055ff"
  Hint: Signature
  Value: "product-content"
- ID: "c7c26117-dbb1-42b2-ab5e-f7223845cca3"
  Hint: __Thumbnail
  Value: |
    <image mediaid="{A956C673-698E-4B66-8E3F-E084E549E64B}" />
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "0a9b643c-9f2c-466c-982d-91bce47adfdb"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{AD23DDC3-B62B-44D0-A062-0811B0F409ED}"
              p:before="*"
              s:id="{7A1D9A21-B8D7-42F9-9B0B-92ABF8D1974F}"
              s:par="GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;FieldNames&amp;BackgroundImage&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=1"
              s:ph="headless-main" />
            <r
              uid="{1CFB0DCB-A7BC-4C14-8F81-22B19BAFBC1C}"
              p:after="r[@uid='{AD23DDC3-B62B-44D0-A062-0811B0F409ED}']"
              s:id="{3836D951-BB14-43AC-9231-649B7F245DC5}"
              s:par="GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;FieldNames=%7B8680041C-1659-4BA5-AFBD-EE5520632E3D%7D&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=3"
              s:ph="/headless-main/container-1" />
            <r
              uid="{401D4009-19B5-469C-ADAD-EAB96A105BFC}"
              p:after="r[@uid='{1CFB0DCB-A7BC-4C14-8F81-22B19BAFBC1C}']"
              s:id="{C5F905F8-FD1F-444E-A9E5-AC6B774FF0DE}"
              s:par="GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;FieldNames=%7B55F5B5E0-CB76-4DE6-94E6-0D048935ED90%7D&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=2"
              s:ph="/headless-main/container-1" />
            <r
              uid="{B78CD88C-6F70-41F4-B41D-841BE027EBEA}"
              p:after="*[1=2]"
              s:id="{7A1D9A21-B8D7-42F9-9B0B-92ABF8D1974F}"
              s:par="GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;FieldNames&amp;BackgroundImage&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=4"
              s:ph="/headless-main/container-1" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250611T061729Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\victor.basurto@brookfieldrp.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\victor.basurto@brookfieldrp.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f3f37562-d84f-49cb-a361-ec66e7df0f19"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\victor.basurto@brookfieldrp.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250611T063307Z
- Language: "fr-CA"
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{6204D75F-665F-4EC1-A95F-F0644EB74122}"
              p:before="*"
              s:id="{7A1D9A21-B8D7-42F9-9B0B-92ABF8D1974F}"
              s:par="GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;FieldNames&amp;BackgroundImage&amp;Styles=%7C%7B4B107495-64E7-4B3E-8F47-A931A1F7CC43%7D&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=1"
              s:ph="headless-main" />
            <r
              uid="{D99F0694-94B9-4198-B717-FDBA571B8CE1}"
              p:after="r[@uid='{6204D75F-665F-4EC1-A95F-F0644EB74122}']"
              s:id="{3836D951-BB14-43AC-9231-649B7F245DC5}"
              s:par="GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;FieldNames=%7B8680041C-1659-4BA5-AFBD-EE5520632E3D%7D&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=2"
              s:ph="/headless-main/container-1" />
            <r
              uid="{B1DE4E49-EA23-48DA-98C8-53BCD60B76ED}"
              p:after="*[1=2]"
              s:id="{C5F905F8-FD1F-444E-A9E5-AC6B774FF0DE}"
              s:par="GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;FieldNames=%7B55F5B5E0-CB76-4DE6-94E6-0D048935ED90%7D&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=3"
              s:ph="/headless-main/container-1" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250611T055246Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\victor.basurto@brookfieldrp.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\victor.basurto@brookfieldrp.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ddf43a6e-789b-422b-8020-696fb90f653b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\victor.basurto@brookfieldrp.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250611T055355Z
