---
ID: "4b674e72-75c8-4dd9-a2d5-05a830e24070"
Parent: "8b035b67-d38e-435f-90a1-d247179d1308"
Template: "8b035b67-d38e-435f-90a1-d247179d1308"
Path: "/sitecore/templates/Project/skate-park/Headless Tenant/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250611T011559Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\victor.basurto@brookfieldrp.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\victor.basurto@brookfieldrp.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "bed74788-f5f4-4cc3-94f5-60e46ca957b6"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\victor.basurto@brookfieldrp.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250611T011559Z
